services:
  - type: web
    name: laravel12-app
    env: docker
    repo: https://github.com/Ashish7428/BookLara.git
    dockerContext: .
    dockerfilePath: Dockerfile
    branch: main
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:LQQjjsq838tw9cUtqicqOQ9mT7ZP5y7FWx2Q9soFtEY=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql12777305
      - key: DB_USERNAME
        value: sql12777305
      - key: DB_PASSWORD
        value: XK89V8rZmY
